#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-plucky
Version  : 0.6.6
Release  : 1
URL      : https://rubygems.org/downloads/plucky-0.6.6.gem
Source0  : https://rubygems.org/downloads/plucky-0.6.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core

%description
# Plucky
Thin layer over the ruby driver that allows you to quickly grab hold of your data (pluck it!).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n plucky-0.6.6
gem spec %{SOURCE0} -l --ruby > rubygem-plucky.gemspec

%build
gem build rubygem-plucky.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
plucky-0.6.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/plucky-0.6.6.gem
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Class/cdesc-Class.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/NilClass/cdesc-NilClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Object/duplicable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/cdesc-CriteriaHash.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/hash_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/key_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/merge_compound_or_clauses%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/merge_values_into_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/modifier_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/normalized_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/normalized_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/object_id%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/object_ids%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/object_ids-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/simple%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/CriteriaHash/value_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/asc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/desc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/exists-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/gt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/gte-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/in-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/lt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/lte-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/mod-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/ne-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/nin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/Symbol/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Extensions/cdesc-Extensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashKey/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashKey/cdesc-CriteriaHashKey.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/cdesc-CriteriaHashValue.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/criteria_hash_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/modifier%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/nesting_operator%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/object_id%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/CriteriaHashValue/to_object_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/FieldsValue/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/FieldsValue/cdesc-FieldsValue.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/HashKey/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/HashKey/cdesc-HashKey.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/HashKey/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/Integer/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/Integer/cdesc-Integer.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/cdesc-OptionsHashValue.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/default_fields_value_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/default_limit_value_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/default_skip_value_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/default_sort_value_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/OptionsHashValue/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/SortValue/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/SortValue/cdesc-SortValue.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/SortValue/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/SortValue/normalized_direction-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/SortValue/normalized_sort_piece-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Normalizers/cdesc-Normalizers.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/cdesc-OptionsHash.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/fields%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/key_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/normalized_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/normalized_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/OptionsHash/value_normalizer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Collection/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Collection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Collection/paginator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/cdesc-Paginator.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/current_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/next_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/out_of_bounds%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/per_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/previous_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/total_entries-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/Paginator/total_pages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Pagination/cdesc-Pagination.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/distinct-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/exist%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/exists%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/find_each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/find_one-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/last-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/only-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/paginate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/per_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/reverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/skip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/sort-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/DSL/where-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/amend-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/cdesc-Query.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/collection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/criteria-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/criteria_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/cursor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/explain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/hash_for_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/initialize_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/object_ids-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/options_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/options_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/set_field_inclusion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/symbolized_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/Query/update-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/cdesc-Plucky.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/modifier%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Plucky/to_object_id-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/cdesc-SymbolOperator.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/SymbolOperator/operator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/plucky-0.6.6/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/README.md
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/UPGRADES
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/examples/query.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/criteria_hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/extensions/duplicable.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/extensions/symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/new_relic.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/criteria_hash_key.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/criteria_hash_value.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/fields_value.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/hash_key.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/integer.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/options_hash_value.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/normalizers/sort_value.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/options_hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/pagination.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/pagination/collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/pagination/paginator.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/query.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/lib/plucky/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/plucky.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/script/bootstrap
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/script/criteria_hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/script/release
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/script/test
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/functional/options_hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/criteria_hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/criteria_hash_key_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/criteria_hash_value_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/fields_value_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/hash_key_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/integer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/options_hash_value_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/normalizers/sort_value_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/options_hash_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/pagination/collection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/pagination/paginator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky/query_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/plucky_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/symbol_operator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/spec/symbol_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/plucky-0.6.6/specs.watchr
/usr/lib64/ruby/gems/2.2.0/specifications/plucky-0.6.6.gemspec
